### ISSUE TITLE
this.getState(modelA)与this.getContainer(modelA).state有没有区别？

### ISSUE THREAD

**Issue by atvoid** [SpringNyan/nyax#12]
this.getState(modelA)与this.getContainer(modelA).state有没有区别？

**Comment by SpringNyan** [comment]
一般来说`getState`是给dynamic model用的。除此之外这两个的区别在于`getState`会返回真实的state，而`container.state`在没有注册的时候会返回默认state

`getState(DynamicModel)`可以得到`Record<string, DynamicModelState>`，在`createSeletor`中可以当作计算的依赖
