### ISSUE TITLE
When a model is being unRegistered, is there anyway that model can know that?

### ISSUE THREAD

**Issue by woohling** [SpringNyan/nyax#24]
There might be some internal cleanup work to do when a model is unRegistered, e.g. cancel onGoing request. For model itself, can it be notified or is there some callback can be used? If no, do you consider adding this kind of support?

For example, React component back in the old days had life cycle like: beforeUnmount, unmount, didUnmount.

**Comment by SpringNyan** [comment]
Generally, there are 2 ways to detect unregistering model:

1. Subscribe `@@nyax/unregister` action in global store, and check if its payload contains the namespace you are interested.

1. Define an epic in your model, then use RxJS `finalize` operator to do somethings when model is unregistering. (epic will be auto completed when model is unregistering)
