### ISSUE TITLE
package name可不可以换个名字

### ISSUE THREAD

**Issue by atvoid** [SpringNyan/nyax#9]
建议package name起个官方点的名字啊，方便推广...也好给别人解释...nyax有点太魔幻了..

**Comment by SpringNyan** [comment]
`nya😼 + x`
一般来说许多类redux框架都用 **x** 来结尾 (vuex, mobx)
前半部分则是看作者个人的喜好了，比如阿里也有 dva, umi 什么的嘛😂

另外类似redux-advanced的名字难以在代码中作symbol还不好记，名字还是简单一些比较好
